== Think and Grow Rich

=== Resumen

Es una explicación larga de cómo dominar y enriquecer la mente. Propone que la mente es la base para generar cualquier tipo de riquezas en tu vida; se usa el dinero como ejemplo de una riqueza tangible y fácil de entender, pero los principios aplican para cualquier otro tipo de riqueza.


=== Lecciones

. Todo comienza con un deso intenso, un deseo que te quema ("burning desire"). Si no lo tienes es probable que no logres mucho.
. Debes convecerte a personalmente de ser capaz de lograr lo que te propusiste. "Tener fe".
. Para lograr algo que deseas tienes que ser persistente, y en algunos momentos de ese camino estarás temporalmente derrotado.
. La mente trabaja de formas que nos conocemos y que pueden parecer mágicas, como el funcionamiento del subconsciente.
. Uno de los peores errores que se pueden cometer es dejarte influenciar negativamente por los demás.
. Obtener conocimiento **específico** es valioso, nadie paga mucho o valora mucho el conocimiento general.
. Para lograr tus metas necesitas energía.


=== Accionables

1. Crea un objetivo detallado sobre lo que quieres lograr, *escríbelo*.

2. 

=== Discusión

-> El autor pasa de cosa bastante lógicas a cosas bastante locas, tal vez como ejemplos pero algunos sacan de onda.

-> Limitar las entradas no estructuradas de información como las opiniones sin la intención de ayudarte, porque te pueden llegar de pensamientos negativos.

->

=== Conclusión

-> Tiene ideas básicas buenas, pero una ejecución bastante extraña.