== Think and Grow Rich

=== Resumen

Es una explicación larga de cómo dominar y enriquecer la mente. Propone que la mente es la base para generar cualquier tipo de riquezas en tu vida; se usa el dinero como ejemplo de una riqueza tangible y fácil de entender, pero los principios aplican para cualquier otro tipo de riqueza.


=== Lecciones

. Todo comienza con un deso intenso, un deseo que te quema (**"burning desire"**). Si no lo tienes es probable que no logres mucho.
. Debes **convecerte a personalmente** de ser capaz de lograr lo que te propusiste. "Tener fe" y auto-sugestión.
. Para lograr algo que deseas tienes que ser persistente, y en algunos momentos de ese camino estarás temporalmente derrotado.
. La mente trabaja de formas que nos conocemos y que pueden parecer mágicas, como el funcionamiento del subconsciente.
. Uno de los peores errores que se pueden cometer es dejarte influenciar negativamente por los demás.
. Obtener conocimiento **específico** es valioso, nadie paga mucho o valora mucho el conocimiento general.
. Para lograr tus metas necesitas energía, que puedes generar manteniéndote en la medida de lo posible saludable y canalizando los deseos naturales.


=== Accionables

. Crea un objetivo detallado sobre lo que quieres lograr, *escríbelo*.
. Crear un grupo estructurado de personas con las cuales empujar el crecimiento.
. Desarrollar conocimiento profundo y específico sobre un tema en partícular:
.. Descubrir qué es rentable
.. Elegir un tema
.. Crear un plan de estudios
.. Recorrer el plan de estudios (Podría aplicar ultralearning)
. Aumentar mi pensamiento positivo reflexionando diariamente en:
.. En lo que quiero lograr
.. En los medios que tengo para lograrlo


=== Discusión

. El autor pasa de cosa bastante lógicas a cosas bastante locas, tal vez como ejemplos pero algunos sacan de onda.

. Los ejemplos usados tienen "la visión del vencedor". Menciona muchos ejemplos de personas ricas que aplicaban los principios que el autor menciona, pero eso no es muestra de que lso principios funcionen porque no da ejemplos de personas "vencidas"

=== Conclusión

Tiene ideas básicas buenas, pero una escritura bastante extraña. Algunas de las ideas están bastante locas como por ejemplo: "el cerebro es una máquina receptora". Vale la pena leer un resumen y tomarlo con un grano de sal.
